spring:
  application:
  name: santander-api-app
  profiles:
    active: prod
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
springdoc:
  override-with-generic-response: false